### ISSUE TITLE
systemd notify support

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs-cluster/ipfs-cluster#1144]
It would be nice to have systemd-notify support, to start applications using ipfs-cluster-service after the service has been successfully started.

IPFS has already support for this service type:

https://github.com/ipfs/go-ipfs/commit/87f2e38017a0965d285a1ab10f64b6afe1277dc3

**Comment by hsanjuan** [comment]
And the default service file should require ipfs to start before cluster itself.

**Comment by RubenKelevra** [comment]
Yes.

I already have a service file created for my server, would just create a PR for it, as soon as notify support is added. :)

**Comment by Luflosi** [comment]
Have you had some time to look at the hardening options yet?

**Comment by hsanjuan** [comment]
Fixed by #1898 I think.
