### ISSUE TITLE
ipfs-cluster-service can't connect to ipfs service right away

### ISSUE THREAD

**Issue by cahlenlee** [ipfs-cluster/ipfs-cluster#1499]
**Additional information:**
 - OS: Ubuntu 20, CentOS 8
 - IPFS Cluster version: 0.14.1
 - Installation method: dist.ipfs.io

**Describe the bug:**

ipfs-cluster-service doesn't connect to ipfs if both are started by systemd at startup.  Even using after=ipfs.service and requires=ipfs.service didn't work. I had to put a pause of 60 seconds before it would connect to the ipfs daemon on startup.

**Comment by hsanjuan** [comment]
If go-ipfs is started with the recommended [systemd service file, which are of type=nofitify](https://github.com/ipfs/go-ipfs/blob/master/misc/systemd/ipfs.service), then after=ipfs.service should wait until go-ipfs is fully ready.

Can you confirm?
