### ISSUE TITLE
Use case: As long-distance replication and offsite backup

### ISSUE THREAD

**Issue by Vaelatern** [ipfs-cluster/ipfs-cluster#157]
Relevant usage:
I wish to have my NAS units be used as backups. While I have RAID on my NAS units, that isn't backup. It also is very little fun to mirror things on the same network, since if the computers get damaged or removed, the backups go with them. Therefore, to increase backup resiliency, offsite backups would be made.

And where would that second backup machine go? Probably right next to other machines desparately in need of backups themselves. Thus, bi-directional backups are now necessary, and a master-slave system will be inadequate. We don't require a true master-master, but definitely one that's more flexible than the likes of Gluster (nothing personal, it just won't work here).

Enter ipfs-cluster.

Despite having a Leader, it seems that any member of the cluster can have something added, and only then does the Leader need to take ownership. While this does not seem suitable for writing to any NAS during extended disconnected operation, it does seem to take ownership of the file without a client needing to figure out which machine is the master.

IPFS gets exposed as a filesystem, allowing local backups with conventional means, such as rsync, to the local NAS unit.

If I want to add new NAS units, or new locations, I can do so without too much difficulty.

Granting access to an IPFS endpoint to end user machines (for backups with the likes of Time Machine or other local backup mechanisms.), becomes a less impossible challenge, since ipfs can be exposed over FUSE.

I have not yet figured out how to go from writing something to my local ipfs to pinning it automatically, but I'm sure it can be done, and it's possible that just writing to files in the FUSE export will be adequate.

---

I appreciate your reading this. Please do let me know if I am barking up the wrong tree with this use case.

**Comment by hsanjuan** [comment]
Hey @Vaelatern , sorry for getting back so late.

Your assumptions are mostly correct. You *could* use ipfs-cluster for this usecase, but it's not tested so it might not work super well at the beginning.

Cluster runs Raft for consensus, which elects a node as leader and cluster transparently redirects pinning requests to that node from wherever they originate. The leader mantains the shared state, which every other node subscribes to. cluster will allow pinning as long as you can elect a leader (%50+1 peers online). Of course, if you have 2 peers, you can manually remove one and then the cluster-size is 1 peer and that one will be the leader.

The main issues you might face (in principle) are related to Raft not behaving well in high latency links (your nodes being far away from each other), as it is not tuned (or user-tunable) to do so. **We'd be really interested to hear your results if you deploy this setup. We're happy to help with any issues.** It's been in my mind  to expose Raft configuration to the user so raft timeouts can be tuned for specific network characteristics.

Regarding rsyncing to NAS drives from fuse-mounted IPFS, yes, it's an option as long as fuse doesn't become a bottleneck.

**Comment by Vaelatern** [comment]
Ah, you may have misunderstood. I intend to back IPFS with my NAS drives, and provide IPFS mounted via FUSE as the interface to foreign machines.

Though with this information, I will need to be very cautious before trusting my data to this mechanism. I'll still try it though.

**Comment by hsanjuan** [comment]
> Though with this information, I will need to be very cautious before trusting my data to this mechanism. I'll still try it though.

Well, your data will not disappear silently or be removed by mistake or anything like that. You will just see errors when pinning or in general (timeouts and such). It should all appear pretty red in the logs. It is something that we'll ourselves will test in our own cluster deployment in the next few weeks too.

**Comment by Vaelatern** [comment]
I will be happy to make my experiences known to you as I establish this mechanism.

**Comment by hsanjuan** [comment]
Hi @Vaelatern , the new `0.2.0` version of cluster allows to customize a number of raft options in the new configuration file (you will need to re-initialize the configs with the new format). Increasing those defaults might be necessary for scenarios with higher latencies which might help you.

**Comment by magneticflux-** [comment]
@Vaelatern I'm looking for solutions to the same problem you had. Could you share some of your experience setting up long-distance replication?

My goal is to establish a P2P network of backups for family in a ~250mi radius. Currently, it operates in a individually-configured master-slave setup.

**Comment by hsanjuan** [comment]
Note, this use-case should be fairly simplified with the `--consensus crdt` mode.

**Comment by RubenKelevra** [comment]
I don't there's any restriction for this usecase anymore. Just make sure to set the replication to -1,-1 to avoid repining the data away from your offline-storage when it goes offline again.

If you run intro trouble, just open a ticket for it :)
