### ISSUE TITLE
Dedicated return value on "deadline exceeded" ('--wait' timeout)

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs-cluster/ipfs-cluster#1675]
**Describe the feature you are proposing**

Currently, an operation might be time-limited and there's a message reporting this back. But it would be great if the return code could be not 1 in this case, but something distinctive to be easily able to identify the reason for the failure - without parsing the message itself.

```console
[ipfs@odin ~]$ ipfs-cluster-ctl pin update --wait --wait-timeout 600s $oldcid $newcid
error waiting for pin status: context deadline exceeded
[ipfs@odin ~]$ echo $?
1
```

**Additional context**

I guess 62 would be the "correct" one:

```console
$ grep "define" /usr/include/asm-generic/*err* | grep -i time
/usr/include/asm-generic/errno.h:#define        ETIME           62      /* Timer expired */
/usr/include/asm-generic/errno.h:#define        ETIMEDOUT       110     /* Connection timed out */
```

Or if this operation is still beeing completed and just the "reporting" is aborted, we might want to use 115 instead.

```console
$ grep "define" /usr/include/asm-generic/*err* | grep -i operation | grep -i -E "progress|canceled"
/usr/include/asm-generic/errno.h:#define        EALREADY        114     /* Operation already in progress */
/usr/include/asm-generic/errno.h:#define        EINPROGRESS     115     /* Operation now in progress */
/usr/include/asm-generic/errno.h:#define        ECANCELED       125     /* Operation Canceled */
```

**Comment by RubenKelevra** [comment]
Or if this operation is still beeing completed and just the "reporting" is aborted, we might want to use 115 instead.


```console
$ grep "define" /usr/include/asm-generic/*err* | grep -i operation | grep -i -E "progress|canceled"
/usr/include/asm-generic/errno.h:#define        EALREADY        114     /* Operation already in progress */
/usr/include/asm-generic/errno.h:#define        EINPROGRESS     115     /* Operation now in progress */
/usr/include/asm-generic/errno.h:#define        ECANCELED       125     /* Operation Canceled */
```

**Comment by hsanjuan** [comment]
Maybe just try 62 and 125 depending on whether it is an error coming from an expired context or from a cancelled context. I think this can be done in the `formatResponse` method.

**Comment by hsanjuan** [comment]
> got it, thanks, Can you please give me write access, I can not able to push my feature branch to the repo for PR.

Please send it from a fork
