### ISSUE TITLE
add 'expire-in-old' setting on 'pin update'

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs-cluster/ipfs-cluster#1677]
**Describe the feature you are proposing**

It would be nice if we could update the old pin, to expire after a certain amount of time, after we ran an 'pin update' command.

This makes sure the old data sticks around long enough to be efficiently updated and only be removed after a grace period, without bothering manually about it.

**Comment by hsanjuan** [comment]
We currently let commands/endpoints perform a single pinset-update operation. This would require a second one. This is very similar to having an `--unpin` flag that would unpin the original pin on update, and same reason why we don't have it, as it muddles the semantics and poses problems (what if the pin update works but the unpin fails?).

In any case, like unpinning, this can be achieved by doing a second command `pin add --expire-in <duration> <old_cid>`, which is a reasonable workaround, imho.
