### ISSUE TITLE
Warning "blockPut response CID xxx does not match the multihash of any blocks sent"

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs-cluster/ipfs-cluster#1706]
**Additional information:**
 - OS: Linux
 - IPFS Cluster Follower version: 1.0.1
 - Installation method: dist.ipfs.io

**Describe the bug:**

Got a lot of warning messages on a GC round on my cluster follower for the ipfs websites. Not sure what that's about but it sounded weird:

[log.txt](https://github.com/ipfs-cluster/ipfs-cluster/files/8928913/log.txt)

**Comment by hsanjuan** [comment]
This means that IPFS adds a block and the response does not match the multihash of any of the blocks told it to add. I have seen this before but I'm not sure why it happens. I wonder if IPFS is streaming back errors somehow.

If you can reproduce it while adding something, I would love to have a file that causes this.

**Comment by RubenKelevra** [comment]
> This means that IPFS adds a block and the response does not match the multihash of any of the blocks told it to add.

Wait, you're saying the cluster isn't streaming car archives to the other IPFS nodes? Why?
