### ISSUE TITLE
error loading cluster secret from config: encoding/hex: invalid byte: U+0077 'w'

### ISSUE THREAD

**Issue by juev** [ipfs-cluster/ipfs-cluster#1726]
**Additional information:**
 - OS: Ubuntu
 - IPFS Cluster version: latest
 - Installation method: docker-compose

**Describe the bug:**

I use [docker-compose](https://github.com/ipfs-cluster/ipfs-cluster/blob/master/docker-compose.yml) from repository without changes. Previously I export `CLUSTER_SECRET` variable with `whataeve` word:

```bash
export CLUSTER_SECRET=whateve
```

then runed cluster with `docker-compose`:

```bash
docker compose up
```

all cluster peers was exited with errors like this:

```plain
cluster0  | error applying environment variables to configuration: error loading cluster secret from config: encoding/hex: invalid byte: U+0077 'w'
```

w - its first symbol from secret in this case. If we export another secret, we see the first symbol from new secret.

If we run `docker compose` with empty secret it running with warning like this:

```plain
cluster2  | 2022-06-24T15:08:28.062Z	WARN	cluster	ipfs-cluster/cluster_config.go:570	Cluster secret is empty, cluster will start on unprotected network.
```

what I missed?

Why I cant to use secret?

**Comment by hsanjuan** [comment]
You missed that the secret is a 320byyte hex-encoded string (https://ipfscluster.io/documentation/guides/security/#the-cluster-secret).

You can generate with `od  -vN 32 -An -tx1 /dev/urandom | tr -d ' \n' | base64 -w 0 -`, for example.
