### ISSUE TITLE
38/5000  100 threads concurrently call to upload 1KB file, and occasionally there is a connection timeout. What configuration should be modified

### ISSUE THREAD

**Issue by caoyanjie890928** [ipfs-cluster/ipfs-cluster#1737]
38/5000 
100 threads concurrently call to upload 1KB file, and occasionally there is a connection timeout. What configuration should be modified

**Comment by hsanjuan** [comment]
Have you followed recommendations here? https://ipfscluster.io/documentation/deployment/setup/#ipfs-configuration

**Comment by caoyanjie890928** [comment]
I started the node with the default configuration，use docker mirror image v1.0.1，What configurations are available to increase the number of connections

**Comment by hsanjuan** [comment]
The documentation has information on how to optimize configurations for production setups. This is a support question so it should go to the forums https://discuss.ipfs.io
