### ISSUE TITLE
Can the ipfs repo stat command be available in ipfsCluster

### ISSUE THREAD

**Issue by jdAction** [ipfs-cluster/ipfs-cluster#1792]
![image](https://user-images.githubusercontent.com/87454525/199459095-340134da-0d79-4338-ab5f-cd89a1c56e4d.png)
Can the ipfs repo stat command be available in ipfsCluster

**Comment by hsanjuan** [comment]
what should this command answer?

**Comment by jdAction** [comment]
Storage utilization of IPFS nodes

**Comment by hsanjuan** [comment]
you can run `ipfs-cluster-ctl health metrics freespace` for that.

**Comment by jdAction** [comment]
This command cannot look at the percentage occupied

**Comment by hsanjuan** [comment]
Maybe you can calculate that if you know how you have configured StorageMax in the IPFS nodes.

**Comment by jdAction** [comment]
Don't know how to do it

**Comment by hsanjuan** [comment]
Why do you need to know the %-used ?

**Comment by jdAction** [comment]
Trigger GC based on percentages
