### ISSUE TITLE
How to stress test, can you provide a tool?

### ISSUE THREAD

**Issue by jdAction** [ipfs-cluster/ipfs-cluster#1805]
To what extent does a node write slowly, to what magnitude does the number of pins it occupy, or does it slow down when it occupies a certain percentage of disk, I need a tool to test its performance

**Comment by jdAction** [comment]
Currently I use http to create requests ,In case of a single node I modified the 
"high_water": 40000,
"low_water": 10000,
"max_pin_queue_size": 1000000,
"concurrent_pins": 1000.
It's still slow

**Comment by jdAction** [comment]
When adding, the default does not pin how to set

**Comment by jdAction** [comment]
Will there be a difference in query speed between a 1T file and a million 1M files in the case of pinning?

**Comment by jdAction** [comment]
![image](https://user-images.githubusercontent.com/87454525/202390269-c597b801-fea4-41f1-a8c2-21b42451cd7e.png)
ipfs-cluster-ctl add /data/ipfs-cluster/b
![image](https://user-images.githubusercontent.com/87454525/202390403-6d48b99b-132c-4eed-9624-21c9d277683c.png)
![image](https://user-images.githubusercontent.com/87454525/202390460-3a2b2aa5-3f24-4fb4-913c-f2e28f813996.png)
Large file upload cores are not full

**Comment by hsanjuan** [comment]
1000 concurrent pins will make IPFS very slow. See https://ipfscluster.io/documentation/deployment/setup/#settings-for-production which recommends between 10-20.

Please ask these questions in https://discuss.ipfs.io. If CPU is not the bottleneck, then the disk is, or the bandwidth.
