### ISSUE TITLE
IPFS Cluster Peers not able to discover each other

### ISSUE THREAD

**Issue by ohmpatel1997** [ipfs-cluster/ipfs-cluster#1806]
I am currently experimenting with setting up the IPFS cluster locally using the docker-compose file mentioned [here](https://raw.githubusercontent.com/ipfs-cluster/ipfs-cluster/master/docker-compose.yml). This is recommended file in the official IPFS cluster documentation [here](https://ipfscluster.io/documentation/quickstart/).

The issue I am facing is, I am able to upload/pin data, but just on one node, i.e cluster0/ipfs0. when i do, peers ls, it shows:

```
12D3KooWKpQhmnaJfMpkbnM9hc5MCHBPzcDLneSCTZir3KfzhEzv | cluster0 | Sees 0 other peers
  > Addresses:
    - /ip4/127.0.0.1/tcp/9096/p2p/12D3KooWKpQhmnaJfMpkbnM9hc5MCHBPzcDLneSCTZir3KfzhEzv
    - /ip4/172.31.0.6/tcp/9096/p2p/12D3KooWKpQhmnaJfMpkbnM9hc5MCHBPzcDLneSCTZir3KfzhEzv
  > IPFS: 12D3KooWQJKdmuErPxaobQMnWMdGPSKeBiJLJ9GYDGz8dgyLmpuY
    - /ip4/127.0.0.1/tcp/4001/p2p/12D3KooWQJKdmuErPxaobQMnWMdGPSKeBiJLJ9GYDGz8dgyLmpuY
    - /ip4/127.0.0.1/udp/4001/quic/p2p/12D3KooWQJKdmuErPxaobQMnWMdGPSKeBiJLJ9GYDGz8dgyLmpuY
    - /ip4/172.31.0.3/tcp/4001/p2p/12D3KooWQJKdmuErPxaobQMnWMdGPSKeBiJLJ9GYDGz8dgyLmpuY
    - /ip4/172.31.0.3/udp/4001/quic/p2p/12D3KooWQJKdmuErPxaobQMnWMdGPSKeBiJLJ9GYDGz8dgyLmpuY
    - /ip4/54.189.89.138/tcp/4001/p2p/12D3KooWNgxATDv46KseNrQZSQ1A1urKKMv9y8rrVGwmVEYdKuPi/p2p-circuit/p2p/12D3KooWQJKdmuErPxaobQMnWMdGPSKeBiJLJ9GYDGz8dgyLmpuY
    - /ip4/54.189.89.138/udp/4001/quic/p2p/12D3KooWNgxATDv46KseNrQZSQ1A1urKKMv9y8rrVGwmVEYdKuPi/p2p-circuit/p2p/12D3KooWQJKdmuErPxaobQMnWMdGPSKeBiJLJ9GYDGz8dgyLmpuY
    - /ip4/66.42.103.205/tcp/4001/p2p/12D3KooWRwEtLndMA7eALuKADnqchPDcDNwbhdhNiFLUkDmaJ9bw/p2p-circuit/p2p/12D3KooWQJKdmuErPxaobQMnWMdGPSKeBiJLJ9GYDGz8dgyLmpuY
    - /ip4/66.42.103.205/udp/4001/quic/p2p/12D3KooWRwEtLndMA7eALuKADnqchPDcDNwbhdhNiFLUkDmaJ9bw/p2p-circuit/p2p/12D3KooWQJKdmuErPxaobQMnWMdGPSKeBiJLJ9GYDGz8dgyLmpuY
    - /ip6/64:ff9b::36bd:598a/tcp/4001/p2p/12D3KooWNgxATDv46KseNrQZSQ1A1urKKMv9y8rrVGwmVEYdKuPi/p2p-circuit/p2p/12D3KooWQJKdmuErPxaobQMnWMdGPSKeBiJLJ9GYDGz8dgyLmpuY
```

As you can see, it is not able to detect other peers.

few notes:

I am setting up the secret correct. its all same across all cluster’s service.json file
I am able to ping the containers from each other, which mean containers can able to talk to each other.
I am using the exactly the same docker-compose file as it is mentioned in the doc.
I think the issue is with the mDNS, I am getting this error/log on all the three cluster:
mDNS could not be started: no supported interface

Please help me out to debug this. Thanks

**Additional information:**
 - OS: MacOS Montery (ARM arch)
 - IPFS Cluster version: latest
 - Installation method: Docker

**Comment by hsanjuan** [comment]
Closing in favour of https://discuss.ipfs.tech/t/ipfs-cluster-peers-not-able-to-discover-each-other/15514.
