### ISSUE TITLE
Can the "ipfs pin update" command be available in IPFS cluster

### ISSUE THREAD

**Issue by sameh-farouk** [ipfs-cluster/ipfs-cluster#1807]
**Describe the feature you are proposing**

Can the IPFS update command be available in IPFS cluster?

**Additional context**

[ipfs update](https://github.com/ipfs/kubo/issues/3754)

**Comment by hsanjuan** [comment]
There is a pin-update operation supported in cluster: `ipfs-cluster-ctl pin update`.

**Comment by sameh-farouk** [comment]
@hsanjuan Thanks for your prompt response. may I ask if it can be used from the go API client? and is there an option to toggle unpinning for the old pin? can you point me to docs where this info is available?

**Comment by hsanjuan** [comment]
As explained here:  https://ipfscluster.io/documentation/reference/api/, you can use `--enc=json --debug` to show how ipfs-cluster-ctl calls the API. In this case it will add a pin-update option to the query arguments.

`/pin/add?pin-update=new-cid&...`
