### ISSUE TITLE
ipfs v0.18: "ipfs does not seem to be available after x retries"

### ISSUE THREAD

**Issue by ShadowJonathan** [ipfs-cluster/ipfs-cluster#1835]
**Additional information:**
 - OS: Debian 10
 - IPFS Cluster version: v1.0.4
 - Installation method: dist.ipfs.io

**Describe the bug:**

I'm not able to have ipfs-cluster access my ipfs instance after upgrading to 0.18, because it constantly errors with "ipfs does not seem to be available after x retries".

I've captured some traffic of an exchange, and here's how the raw TCP stream looks like (output from wireguard):

<details>
<summary>Details</summary>

```http
POST /api/v0/id HTTP/1.1
Host: 127.0.0.1:5001
User-Agent: Go-http-client/1.1
Content-Length: 0
Content-Type: 
Accept-Encoding: gzip

HTTP/1.1 200 OK
Access-Control-Allow-Headers: X-Stream-Output, X-Chunked-Output, X-Content-Length
Access-Control-Expose-Headers: X-Stream-Output, X-Chunked-Output, X-Content-Length
Content-Type: application/json
Server: kubo/0.18.0
Trailer: X-Stream-Error
Vary: Origin
Date: Mon, 23 Jan 2023 19:56:34 GMT
Transfer-Encoding: chunked

b3b
{"ID":"[REDACTED]","PublicKey":"[REDACTED]","Addresses":["[REDACTED]"],"AgentVersion":"kubo/0.18.0/675037721-dirty","ProtocolVersion":"ipfs/0.1.0","Protocols":["/ipfs/bitswap","/ipfs/bitswap/1.0.0","/ipfs/bitswap/1.1.0","/ipfs/bitswap/1.2.0","/ipfs/id/1.0.0","/ipfs/id/push/1.0.0","/ipfs/kad/1.0.0","/ipfs/lan/kad/1.0.0","/ipfs/ping/1.0.0","/libp2p/autonat/1.0.0","/libp2p/circuit/relay/0.1.0","/libp2p/circuit/relay/0.2.0/hop","/libp2p/circuit/relay/0.2.0/stop","/libp2p/dcutr","/p2p/id/delta/1.0.0","/x/"]}

0
```

</details>

The error is thrown away [here](https://github.com/ipfs-cluster/ipfs-cluster/blob/38b463d65836bba818d9a1018416109c5d5bfec0/ipfsconn/ipfshttp/ipfshttp.go#L261), and so i can't report it even if i had debug logs on (which i did enable).

**Comment by hsanjuan** [comment]
The error with v0.18.0 seems to be:

```
failed to parse multiaddr "/ip6/::1/udp/4001/quic-v1/webtransport/certhash/[...]": unknown protocol quic-v1
```

We will have to fix this for next release. Disabling quic/webstransport might be a workaround.
