### ISSUE TITLE
ipfs-cluster-service_v1.0.5 appears to have built incompletely (numerous arch/platforms)

### ISSUE THREAD

**Issue by bhodgens** [ipfs-cluster/ipfs-cluster#1851]
Numerous builds, but specific to my own interest, the ARM 32bit build appears to have not built any binaries: 

https://dist.ipfs.tech/ipfs-cluster-service/v1.0.5/ipfs-cluster-service_v1.0.5_linux-arm.tar.gz

This file only contains license/text files: 

x ipfs-cluster-service/LICENSE
x ipfs-cluster-service/LICENSE-APACHE
x ipfs-cluster-service/LICENSE-MIT
x ipfs-cluster-service/README.md

A quick perusal suggests that this is true for several other builds as well: 

[ipfs-cluster-service_v1.0.5_freebsd-arm.tar.gz](https://dist.ipfs.tech/ipfs-cluster-service/v1.0.5/ipfs-cluster-service_v1.0.5_freebsd-arm.tar.gz)
[ipfs-cluster-service_v1.0.5_linux-386.tar.gz](https://dist.ipfs.tech/ipfs-cluster-service/v1.0.5/ipfs-cluster-service_v1.0.5_linux-386.tar.gz)
[ipfs-cluster-service_v1.0.5_openbsd-386.tar.gz](https://dist.ipfs.tech/ipfs-cluster-service/v1.0.5/ipfs-cluster-service_v1.0.5_openbsd-386.tar.gz)
[ipfs-cluster-service_v1.0.5_openbsd-amd64.tar.gz](https://dist.ipfs.tech/ipfs-cluster-service/v1.0.5/ipfs-cluster-service_v1.0.5_openbsd-amd64.tar.gz)
[ipfs-cluster-service_v1.0.5_openbsd-arm.tar.gz](https://dist.ipfs.tech/ipfs-cluster-service/v1.0.5/ipfs-cluster-service_v1.0.5_openbsd-arm.tar.gz)

**Comment by hsanjuan** [comment]
See https://github.com/ipfs-cluster/ipfs-cluster/issues/1844

**Comment by hsanjuan** [comment]
Hello @bhodgens , there are new builds in dist.ipfs.io for the new release and these os/arch combinations should be fixed. You won't be able to use the pebble backend though.
