### ISSUE TITLE
MaxConcurrentCompactions is missing from Pebble json config

### ISSUE THREAD

**Issue by hsanjuan** [ipfs-cluster/ipfs-cluster#1895]
Due to oversight, this seems to be missing and cannot be customized.

**Comment by arthurgavazza** [comment]
@hsanjuan can I pick this up? Any tips on where to start?

**Comment by hsanjuan** [comment]
> @hsanjuan can I pick this up? Any tips on where to start?

Thanks, just need to be added to these two methods: https://github.com/ipfs-cluster/ipfs-cluster/blob/master/datastore/pebble/config.go#L112-L160
