### ISSUE TITLE
ipfs cluster have  a Default management webUi？

### ISSUE THREAD

**Issue by Alvin-4550** [ipfs-cluster/ipfs-cluster#1902]
Dear everyone

I deployed an ipfs cluster node using Docker Compose, and the ipfs cluster clt has been verified to function properly. It is possible to pin files to the ipfs private cluster. When I tried to open http://<ip>: 9094/webui, a 404 prompt appeared, as follows:

{"code":404,"message":"not found"}

I am a beginner who wants to better understand and learn through a webui interface, but this error has troubled me. Was it removed or was it not enabled due to my lack of configuration.

Thank you very much for seeing my question. If you know what's going on and let me know, I would be very grateful.

**Additional information:**
 - OS: [e.g. Linux]
 - IPFS Cluster version: [e.g. 0.10.1, master]
 - Installation method: [e.g. built from source, dist.ipfs.io, docker]

**Describe the bug:**

A clear and concise description of what the bug is and how the behavior was different from expected.

**Comment by hsanjuan** [comment]
IPFS Cluster does not have a graphical or web UI. If you google you can find some, but they are from third parties and probably unmaintained.

**Comment by Alvin-4550** [comment]
@hsanjuan  Thank you for your answer
