### ISSUE TITLE
I can't disable unpin parameter for the ipfshttp in docker compose file?

### ISSUE THREAD

**Issue by behruzrahimov** [ipfs-cluster/ipfs-cluster#1920]
```
 environment:
    CLUSTER_IPFSHTTP_UNPINDISABLE: true
```
this doesn't work

**Comment by hsanjuan** [comment]
That works, however perhaps not as you expect.

Any cluster-unpin still proceeds, however it is the unpin (pin rm) call to IPFS that will be blocked. So ipfs-cluster-ctl status --filter unpin_error will show errors in unpin operations. When this option is enabled, no unpins calls are made to IPFS, however the cluster "unpins". 

The unpinning process is similar to the pinning process described here: https://ipfscluster.io/documentation/guides/pinning/#the-pinning-process

In this case, the "IPFS unpinning stage" is what is blocked, not the cluster unpinning stage.
