### ISSUE TITLE
IPFS cluster client's add endpoint's response

### ISSUE THREAD

**Issue by trinayanbhatt** [ipfs-cluster/ipfs-cluster#1932]
Hi Team,

I was trying to add multiple files by calling the add endpoint of the IPFS-cluster go client and the API response is multiple structs like this: 

```
{
    "name": "dummy.txt",
    "cid": "QmS21GuXiRMvJKHos4ZkEmQDmRBqRaF5tQS2CQCu2ne9sY",
    "size": 14,
    "allocations": [
        "12xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxqbxRX",
        "12xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvz",
        "12xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkN"
    ]
}
{
    "name": "dummy2.txt",
    "cid": "QmS21GuXiRMvJKHhas4ZkEmQDmRBqRaF5tQS2CQCu2ne9sY",
    "size": 16,
    "allocations": [
        "12xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxqbxRX",
        "12xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvz",
        "12xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkN"
    ]
}
```

As it's not a properly formatted response something more appropriate would be an array of structs, so is it on purpose to provide such a response or is there already some modifications done for properly formatting the response output?

**Comment by hsanjuan** [comment]
This is the Kubo-api output which we mimic.

That said, this is an streaming endpoint, so this format makes sense that that every object can be sent as they get produced. It allows processing the data as it comes, without having to buffer and wait for a JSON-array to be properly closed before you can start decoding the JSON. All the API endpoints that deal with collections of things do it this way.

However, if you pass `?no-stream=true`  or set `--no-stream`
