### ISSUE TITLE
Error while adding multiple files in the IPFS cluster based private network

### ISSUE THREAD

**Issue by tkb2501** [ipfs-cluster/ipfs-cluster#1937]
Hi team,

I have setup a private IPFS cluster based network for decentralized files storage, and I'm using IPFS-Cluster-http client for adding files into the network. I have a setup of 3 cluster nodes and correspondingly 1 IPFS node against each of the Cluster node.

Now while adding multiple files using the /add API I'm getting the output of the stream data with multiple CIDs, but while I'm searching for those CIDs in my cluster node using:

**`ipfs-cluster-ctl pin ls | grep "[CID]"`**

I'm not able to fetch the details corresponding to passed CID, but while fetching the file using get API call by passing the given CID
I'm able to retrieve the file.

And, while I'm trying to pin the CID manually by using:

**`ipfs-cluster-ctl  pin add  [CID]`**

then I'm getting this error:

**`/data/ipfs/datastore/368613.log: no space left on device`**

Even I have checked for the disk space and it is not full, can someone please help me with the issue?

**Comment by hsanjuan** [comment]
> Even I have checked for the disk space and it is not full

The disk on which that file sits is full. Closing in favour of https://github.com/ipfs-cluster/ipfs-cluster/issues/1946
