### ISSUE TITLE
Error in adding and removing files from IPFS nodes

### ISSUE THREAD

**Issue by tkb2501** [ipfs-cluster/ipfs-cluster#1945]
Hi Team,

I have created a IPFS-cluster based private network setup, where I have three IPFS nodes. 

I'm having issues while adding and removing files from IPFS node. So, I have checked for the docker logs and have found this error log continuously generating in IPFS node:

**`ERROR   providers       providers/providers_manager.go:171      error reading providers: committing batch to datastore at /: write /data/ipfs/datastore/368613.log: no space left on device`**

Can someone please help me with the issue as I'm stuck for a long time now.

**Comment by hsanjuan** [comment]
The disk is full.
