### ISSUE TITLE
Does ipfs-cluster support byzantine tolerance?

### ISSUE THREAD

**Issue by sdjasj** [ipfs-cluster/ipfs-cluster#1956]
Does the current version of ipfs-cluster allow the existence of malicious nodes?

**Comment by sdjasj** [comment]
> Does the current version of ipfs-cluster allow the existence of malicious nodes?

More specific, Does the current version of ipfs-cluster using CRDT allow the existence of malicious nodes?

**Comment by sdjasj** [comment]
> Does the current version of ipfs-cluster allow the existence of malicious nodes?

More specifically, Does the current version of ipfs-cluster using CRDT allow the existence of malicious nodes?

**Comment by hsanjuan** [comment]
No, both Raft and CRDT are not byzantine tolerant methods.

Untrusted peers in CRDT mode however should not be able to affect the global state/replication.
