### ISSUE TITLE
v1.0.7 - [FATAL tini (7)] exec /usr/local/bin/custom-entrypoint.sh failed: Exec format error 

### ISSUE THREAD

**Issue by roderik** [ipfs-cluster/ipfs-cluster#1985]
**Additional information:**
 - OS: [e.g. Linux]
 - IPFS Cluster version: [e.g. 0.10.1, master]
 - Installation method: [e.g. built from source, dist.ipfs.io, docker]

**Describe the bug:**

Upgraded docker image 1.0.6 to 1.0.7 on an AMD64 kubernetes cluster and ipfs container no longer starts due to `[FATAL tini (7)] exec /usr/local/bin/custom-entrypoint.sh failed: Exec format error`. I think the amd binary is actually an arm binary

**Comment by acejam** [comment]
I'm also seeing this when attempting to upgrade from `1.0.6` to `1.0.7`.

In addition, it appears the Docker image tag for is now prefixed with a `v`, ie: `v1.0.7` instead of `1.0.6`

**Comment by hsanjuan** [comment]
All the architectures are part of the multiarch container. Have you checked your docker version is not too old or something?
