### ISSUE TITLE
Connection to Kubo via Unix domain socket fails with HTTP error

### ISSUE THREAD

**Issue by ntninja** [ipfs-cluster/ipfs-cluster#1999]
**Additional information:**
 - OS: NixOS 23.05
 - IPFS Cluster version: 1.0.6
 - Installation method: NixOS repo

**Describe the bug:**

When setting `ipfs_connector.ipfshttp.node_multiaddr` to the Multiaddr of the Unix domain socket exposed by Kubo Nix package by default (`"/unix/run/ipfs.sock"`) IPFS Cluster Service appears to successfully connect to the socket but fails to make any HTTP requests instead printing the following error for each request:

> error posting to IPFS:Post "http:///run/ipfs.sock/api/v0/id": http: no Host in request URL

This is probably an encoding issue when generating the URL before passing it to whatever HTTP library is used by ipfs-cluster-service, since the encoded “request URL” should read as “http://%2Frun%2Fipfs.sock/api/v0/id” according to that URL RFC and hence have a hostname (even if unusual) set.

**Comment by hsanjuan** [comment]
@ntninja can you try #2001 ?

**Comment by ntninja** [comment]
Will do soon! Thanks!
