### ISSUE TITLE
ipfs-cluster doesn't maintain /dns4 ipfshttp.node_multiaddress entries as DNS addresses.

### ISSUE THREAD

**Issue by pbennett** [ipfs-cluster/ipfs-cluster#2004]
**Additional information:**
 - OS: Linux (ipfs/ipfs-cluster docker image)
 - IPFS Cluster version: 1.0.7

**Describe the bug:**

I configured ipfs-cluster paired with ipfs nodes, using addresses like: /dns4/xxxxx.yy.zz/tcp/5001.
The cluster properly connects to the ipfs cluster at that DNS address.  However, it appears to simply resolve the IP and then change its connection to be a /ip4/a.b.c.d/...

If the IP address of the IPFS peer changes, then upon the ipfs cluster reconnecting, it doesn't resolve via dns but instead tries to only connect to the previously determined IP address.  If the IP address of the ipfs instance has changed (for example in a k8s cluster where the pod has been re-deployed because of node changes, outages, ..) then the cluster will never reconnect.  Restarting the cluster is the only way to get the cluster to reconnect even though the cluster would have reconnected correctly had it used the dns value it was configured to use.

**Comment by hsanjuan** [comment]
It may be just matter of deleting https://github.com/ipfs-cluster/ipfs-cluster/blob/f1028214cd119ff434058bbce6548f2974bf5588/ipfsconn/ipfshttp/ipfshttp.go#L145-L155
