### ISSUE TITLE
Cannot install on Linux Fedora 40 from source

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [ipfs-cluster/ipfs-cluster#2052]
**Describe the bug:**

make install gives

go: downloading github.com/kishansagathiya/go-dot v0.1.0
graph.go:9:2: reading github.com/kishansagathiya/go-dot/go.mod at revision v0.1.0: git ls-remote -q origin in /root/go/pkg/mod/cache/vcs/0984fd59e6b4c7ab7bbd08ed009bd7fd280c3ab064deedd71f8f16de121de312: exit status 128:

        (gnome-ssh-askpass:49225): Gtk-WARNING **: 00:43:24.745: cannot open display:
        error: unable to read askpass response from '/usr/libexec/openssh/gnome-ssh-askpass'
        fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information

Any idea? thanks

**Comment by hsanjuan** [comment]
Thank you, it seems one of our deps 404s. I will fix this.

**Comment by hsanjuan** [comment]
@kishansagathiya it seems you remove the repo... I have a copy of the code, but if you have it around I could keep the commit history in a fork.

**Comment by kishansagathiya** [comment]
> but if you have it around I could keep the commit history in a fork.

I don't have a copy. I must have deleted this couple of months ago, without realizing that it was being used here. I have looked at [Deleted Repositories](https://docs.github.com/en/repositories/creating-and-managing-repositories/restoring-a-deleted-repository) section in GitHub. Unfortunately, that repo is not recoverable.

But, I see that you were able to fix it quickly so probably not a big deal. Cheers!
