### ISSUE TITLE
Daemon startup logs should mention what components have been chosen

### ISSUE THREAD

**Issue by lanzafame** [ipfs-cluster/ipfs-cluster#881]
It should be clear in the startup logs which consensus component is being used. As well as any other component that has a set of options.

_Originally posted by @lanzafame in https://github.com/ipfs/ipfs-cluster/pull/874/review_comment/create_

**Comment by kishansagathiya** [comment]
APIs are optional components.

Though we don't explicitly say in log, which of these components exist, they give it away.

You see this only if proxy is created
```
15:22:33.189  INFO  ipfsproxy: IPFS Proxy: /ip4/127.0.0.1/tcp/9095 -> /ip4/127.0.0.1/tcp/5001 ipfsproxy.go:278
```
for rest api
```
15:22:33.190  INFO    restapi: REST API (libp2p-http): ENABLED. Listening on:

```
for raft
```
14:17:20.851  INFO       raft: initializing raft cluster with the following voters:

```
for crdt
```
15:23:48.459  INFO       crdt: crdt Datastore created. Number of heads: 0. Current max-height: 0 crdt.go:262
```

Do we still add another log message? I think we should avoid it.

**Comment by hsanjuan** [comment]
We could log the configuration object used by the component in debug mode.

In fact, we should rework the logging to be able to select specific components for debugging...

**Comment by hsanjuan** [comment]
debug logging already logs the full working-configuration used. closing this.
