### ISSUE TITLE
Add metric to expose number of cids pinning

### ISSUE THREAD

**Issue by lanzafame** [ipfs-cluster/ipfs-cluster#897]

**Comment by hsanjuan** [comment]
To be addressed with #898. The idea is to have gauges that show how many items are "queue_pin,queue_unpin,pinned,pinning,unpinning,error_pin..etc" (basically per type of TrackerStatus.

**Comment by kishansagathiya** [comment]
count all tracker statuses on pintracker.StatusAll() and record?

**Comment by hsanjuan** [comment]
My guess is the operation tracker can carry stats as operations are performed.

**Comment by hsanjuan** [comment]
Done around v1.
