### ISSUE TITLE
"go: error loading module requirements" when installing ipfs-cluster on Raspberry Pi

### ISSUE THREAD

**Issue by emclab** [ipfs-cluster/ipfs-cluster#995]
**Additional information:**
 - Raspberry Pi : cat /etc/debian_version
                          10.2
- go version go1.13.6 linux/arm
 - IPFS Cluster version: 0.12.1, master
 - Installation with git clone: git clone https://github.com/ipfs/ipfs-cluster.git

**Describe the bug:**
"go: error loading module requirements" when sudo go install ./cmd/ipfs-cluster-service

go: finding github.com/ipfs/go-verifcid v0.0.1
go: finding github.com/davecgh/go-spew v1.1.0
go: finding golang.org/x/lint v0.0.0-20190301231843-5614ed5bae6f
go: finding github.com/go-logfmt/logfmt v0.4.0
go: finding github.com/spf13/cobra v0.0.5
go: finding go.opencensus.io v0.20.1
go: finding github.com/kr/text v0.1.0
go: finding github.com/libp2p/go-libp2p-secio v0.1.0
go: github.com/spf13/cobra@v0.0.5: unknown revision v0.0.5
go: finding github.com/warpfork/go-wish v0.0.0-20190328234359-8b3e70f8e830
go: finding google.golang.org/grpc v1.22.0
go: finding github.com/mwitkow/go-conntrack v0.0.0-20161129095857-cc309e4a2223
go: finding github.com/mattn/go-isatty v0.0.5
go: finding github.com/DataDog/datadog-go v2.2.0+incompatible
go: finding github.com/circonus-labs/circonus-gometrics v2.3.1+incompatible
go: finding golang.org/x/sync v0.0.0-20181221193216-37e7f081c4d4
go: finding github.com/smartystreets/goconvey v0.0.0-20190330032615-68dc04aab96a
go: finding github.com/libp2p/go-mplex v0.1.0
go: finding github.com/davidlazar/go-crypto v0.0.0-20170701192655-dcfb0a7ac018
go: finding github.com/hashicorp/go-retryablehttp v0.5.3
go: finding github.com/polydawn/refmt v0.0.0-20190408063855-01bf1e26dd14
go: finding golang.org/x/crypto v0.0.0-20190513172903-22d7a77e9e5f
go: error loading module requirements

The installation is following the instruction of "Installing from source" on https://cluster.ipfs.io/download/

**Comment by hsanjuan** [comment]
Try setting `export GOPROXY=off`. I don't know why it complains on `go: github.com/spf13/cobra@v0.0.5: unknown revision v0.0.5` since there is such a tag for that library.

**Comment by emclab** [comment]
There seem some progress made with `export GOPROXY=off`. This time the error is about `build github.com/ipfs/ipfs-cluster/cmd/ipfs-cluster-service: cannot find module for path crypto/ed25519`


go: downloading github.com/miekg/dns v1.1.12
go: downloading github.com/ipfs/go-verifcid v0.0.1
go: downloading github.com/Stebalien/go-bitfield v0.0.1
go: downloading google.golang.org/genproto v0.0.0-20190425155659-357c62f0e4bb
go: downloading github.com/ipfs/go-peertaskqueue v0.1.1
go: downloading github.com/hashicorp/raft v1.1.1
go: downloading github.com/whyrusleeping/mafmt v1.2.8
go: downloading github.com/libp2p/go-libp2p-nat v0.0.4
go: downloading github.com/ugorji/go v1.1.7
go: downloading github.com/libp2p/go-libp2p-consensus v0.0.1
go: downloading github.com/ipfs/go-todocounter v0.0.1
go: downloading github.com/vishvananda/netns v0.0.0-20190625233234-7109fa855b0f
go: downloading github.com/cskr/pubsub v1.0.2
go: downloading github.com/marten-seemann/qtls v0.4.1
go: downloading github.com/AndreasBriese/bbloom v0.0.0-20190306092124-e2d15f34fcf9
go: downloading github.com/marten-seemann/chacha20 v0.2.0
go: downloading github.com/whyrusleeping/go-keyspace v0.0.0-20160322163242-5b898ac5add1
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/ugorji/go/codec v1.1.7
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/gorilla/websocket v1.4.1
go: downloading github.com/whyrusleeping/multiaddr-filter v0.0.0-20160516205228-e903e4adabd7
go: downloading github.com/russross/blackfriday v1.5.2
go: downloading github.com/cenkalti/backoff v2.2.1+incompatible
go: downloading github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: downloading contrib.go.opencensus.io/exporter/prometheus v0.1.0
go: downloading github.com/ipfs/go-ipfs-chunker v0.0.1
go: downloading github.com/libp2p/go-nat v0.0.3
go: downloading github.com/whyrusleeping/go-logging v0.0.0-20170515211332-0457bb6b88fc
go: downloading github.com/whyrusleeping/go-notifier v0.0.0-20170827234753-097c5d47330f
go: downloading github.com/ipfs/go-cidutil v0.0.2
go: downloading github.com/ipfs/go-ipfs-pq v0.0.1
go: downloading github.com/ipfs/go-mfs v0.1.1
go: downloading github.com/huin/goupnp v1.0.0
go: downloading github.com/koron/go-ssdp v0.0.0-20180514024734-4a0ed625a78b
go: downloading github.com/jackpal/gateway v1.0.5
go: downloading golang.org/x/sync v0.0.0-20190423024810-112230192c58
go: downloading github.com/jackpal/go-nat-pmp v1.0.1
go: downloading github.com/whyrusleeping/chunker v0.0.0-20181014151217-fe64bd25879f
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/armon/go-metrics v0.0.0-20190430140413-ec5e00d3c878
go: downloading github.com/ipfs/bbloom v0.0.4
go: downloading gonum.org/v1/gonum v0.0.0-20190926113837-94b2bbd8ac13
go: downloading github.com/hashicorp/go-immutable-radix v1.0.0
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
build github.com/ipfs/ipfs-cluster/cmd/ipfs-cluster-service: cannot find module for path crypto/ed25519

**Comment by emclab** [comment]
Here is output of `go env`:

 $ go env
warning: GOPATH set to GOROOT (/usr/local/go) has no effect
GO111MODULE="on"
GOARCH="arm"
GOBIN=""
GOCACHE="/home/pi/.cache/go-build"
GOENV="/home/pi/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/usr/local/go"
GOPRIVATE=""
GOPROXY="off"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="6"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/pi/ipfs-cluster/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build079944176=/tmp/go-build -gno-record-gcc-switches"

**Comment by hsanjuan** [comment]
So I'm testing on my raspberry Pi and I have no trouble downloading the modules. Verify that you are building with go1.13. `cannot find module for path crypto/ed25519` should certainly be available as that is part of the standard lib I think (check you correctly installed).
